// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: admin.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminUserService_GetAdminUserInfo_FullMethodName  = "/lotus.AdminUserService/GetAdminUserInfo"
	AdminUserService_GetAdminUserList_FullMethodName  = "/lotus.AdminUserService/GetAdminUserList"
	AdminUserService_GetAllDepartments_FullMethodName = "/lotus.AdminUserService/GetAllDepartments"
)

// AdminUserServiceClient is the client API for AdminUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminUserService 管理后台用户相关操作
type AdminUserServiceClient interface {
	// GetAdminUserInfo 根据用户 ID 查询用户信息
	GetAdminUserInfo(ctx context.Context, in *GetAdminUserReq, opts ...grpc.CallOption) (*GetAdminUserResp, error)
	// GetAdminUserList 根据用户 ID 列表查询用户信息列表
	GetAdminUserList(ctx context.Context, in *GetAdminUserListReq, opts ...grpc.CallOption) (*GetAdminUserListResp, error)
	// GetAllDepartments 根据目录查询部门列表
	GetAllDepartments(ctx context.Context, in *GetAllDepartmentReq, opts ...grpc.CallOption) (*GetAllDepartmentResppone, error)
}

type adminUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminUserServiceClient(cc grpc.ClientConnInterface) AdminUserServiceClient {
	return &adminUserServiceClient{cc}
}

func (c *adminUserServiceClient) GetAdminUserInfo(ctx context.Context, in *GetAdminUserReq, opts ...grpc.CallOption) (*GetAdminUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminUserResp)
	err := c.cc.Invoke(ctx, AdminUserService_GetAdminUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUserServiceClient) GetAdminUserList(ctx context.Context, in *GetAdminUserListReq, opts ...grpc.CallOption) (*GetAdminUserListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdminUserListResp)
	err := c.cc.Invoke(ctx, AdminUserService_GetAdminUserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUserServiceClient) GetAllDepartments(ctx context.Context, in *GetAllDepartmentReq, opts ...grpc.CallOption) (*GetAllDepartmentResppone, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllDepartmentResppone)
	err := c.cc.Invoke(ctx, AdminUserService_GetAllDepartments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminUserServiceServer is the server API for AdminUserService service.
// All implementations must embed UnimplementedAdminUserServiceServer
// for forward compatibility.
//
// AdminUserService 管理后台用户相关操作
type AdminUserServiceServer interface {
	// GetAdminUserInfo 根据用户 ID 查询用户信息
	GetAdminUserInfo(context.Context, *GetAdminUserReq) (*GetAdminUserResp, error)
	// GetAdminUserList 根据用户 ID 列表查询用户信息列表
	GetAdminUserList(context.Context, *GetAdminUserListReq) (*GetAdminUserListResp, error)
	// GetAllDepartments 根据目录查询部门列表
	GetAllDepartments(context.Context, *GetAllDepartmentReq) (*GetAllDepartmentResppone, error)
	mustEmbedUnimplementedAdminUserServiceServer()
}

// UnimplementedAdminUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminUserServiceServer struct{}

func (UnimplementedAdminUserServiceServer) GetAdminUserInfo(context.Context, *GetAdminUserReq) (*GetAdminUserResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminUserInfo not implemented")
}
func (UnimplementedAdminUserServiceServer) GetAdminUserList(context.Context, *GetAdminUserListReq) (*GetAdminUserListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdminUserList not implemented")
}
func (UnimplementedAdminUserServiceServer) GetAllDepartments(context.Context, *GetAllDepartmentReq) (*GetAllDepartmentResppone, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllDepartments not implemented")
}
func (UnimplementedAdminUserServiceServer) mustEmbedUnimplementedAdminUserServiceServer() {}
func (UnimplementedAdminUserServiceServer) testEmbeddedByValue()                          {}

// UnsafeAdminUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminUserServiceServer will
// result in compilation errors.
type UnsafeAdminUserServiceServer interface {
	mustEmbedUnimplementedAdminUserServiceServer()
}

func RegisterAdminUserServiceServer(s grpc.ServiceRegistrar, srv AdminUserServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminUserService_ServiceDesc, srv)
}

func _AdminUserService_GetAdminUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUserServiceServer).GetAdminUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUserService_GetAdminUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUserServiceServer).GetAdminUserInfo(ctx, req.(*GetAdminUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminUserService_GetAdminUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminUserListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUserServiceServer).GetAdminUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUserService_GetAdminUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUserServiceServer).GetAdminUserList(ctx, req.(*GetAdminUserListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminUserService_GetAllDepartments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllDepartmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUserServiceServer).GetAllDepartments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUserService_GetAllDepartments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUserServiceServer).GetAllDepartments(ctx, req.(*GetAllDepartmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminUserService_ServiceDesc is the grpc.ServiceDesc for AdminUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lotus.AdminUserService",
	HandlerType: (*AdminUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdminUserInfo",
			Handler:    _AdminUserService_GetAdminUserInfo_Handler,
		},
		{
			MethodName: "GetAdminUserList",
			Handler:    _AdminUserService_GetAdminUserList_Handler,
		},
		{
			MethodName: "GetAllDepartments",
			Handler:    _AdminUserService_GetAllDepartments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
