// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: admin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 操作是否成功
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`       // 错误码
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`  // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AdminUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Tel           string                 `protobuf:"bytes,7,opt,name=tel,proto3" json:"tel,omitempty"`
	State         int32                  `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminUser) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUser) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AdminUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminUser) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *AdminUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AdminUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminUser) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *AdminUser) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type GetAdminUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminUserReq) Reset() {
	*x = GetAdminUserReq{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminUserReq) ProtoMessage() {}

func (x *GetAdminUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminUserReq.ProtoReflect.Descriptor instead.
func (*GetAdminUserReq) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdminUserReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetAdminUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *AdminUser             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminUserResp) Reset() {
	*x = GetAdminUserResp{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminUserResp) ProtoMessage() {}

func (x *GetAdminUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminUserResp.ProtoReflect.Descriptor instead.
func (*GetAdminUserResp) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdminUserResp) GetData() *AdminUser {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetAdminUserResp) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetAdminUserListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []string               `protobuf:"bytes,1,rep,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminUserListReq) Reset() {
	*x = GetAdminUserListReq{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminUserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminUserListReq) ProtoMessage() {}

func (x *GetAdminUserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminUserListReq.ProtoReflect.Descriptor instead.
func (*GetAdminUserListReq) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetAdminUserListReq) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

type GetAdminUserListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*AdminUser           `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminUserListResp) Reset() {
	*x = GetAdminUserListResp{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminUserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminUserListResp) ProtoMessage() {}

func (x *GetAdminUserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminUserListResp.ProtoReflect.Descriptor instead.
func (*GetAdminUserListResp) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GetAdminUserListResp) GetData() []*AdminUser {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetAdminUserListResp) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// department 部门
type Department struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Brief         string                 `protobuf:"bytes,3,opt,name=brief,proto3" json:"brief,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Catalog       string                 `protobuf:"bytes,5,opt,name=catalog,proto3" json:"catalog,omitempty"`
	Leader        []*AdminUser           `protobuf:"bytes,6,rep,name=leader,proto3" json:"leader,omitempty"`
	Member        []*AdminUser           `protobuf:"bytes,7,rep,name=member,proto3" json:"member,omitempty"`
	Children      []*Department          `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *Department) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Department) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Department) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *Department) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *Department) GetCatalog() string {
	if x != nil {
		return x.Catalog
	}
	return ""
}

func (x *Department) GetLeader() []*AdminUser {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *Department) GetMember() []*AdminUser {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *Department) GetChildren() []*Department {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetAllDepartmentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalog       string                 `protobuf:"bytes,1,opt,name=catalog,proto3" json:"catalog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDepartmentReq) Reset() {
	*x = GetAllDepartmentReq{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDepartmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDepartmentReq) ProtoMessage() {}

func (x *GetAllDepartmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDepartmentReq.ProtoReflect.Descriptor instead.
func (*GetAllDepartmentReq) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllDepartmentReq) GetCatalog() string {
	if x != nil {
		return x.Catalog
	}
	return ""
}

type GetAllDepartmentResppone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Department          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDepartmentResppone) Reset() {
	*x = GetAllDepartmentResppone{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDepartmentResppone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDepartmentResppone) ProtoMessage() {}

func (x *GetAllDepartmentResppone) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDepartmentResppone.ProtoReflect.Descriptor instead.
func (*GetAllDepartmentResppone) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllDepartmentResppone) GetData() []*Department {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetAllDepartmentResppone) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\x05lotus\"P\n" +
	"\x06Status\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xad\x01\n" +
	"\tAdminUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x10\n" +
	"\x03tel\x18\a \x01(\tR\x03tel\x12\x14\n" +
	"\x05state\x18\b \x01(\x05R\x05state\"#\n" +
	"\x0fGetAdminUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"_\n" +
	"\x10GetAdminUserResp\x12$\n" +
	"\x04data\x18\x01 \x01(\v2\x10.lotus.AdminUserR\x04data\x12%\n" +
	"\x06status\x18\x02 \x01(\v2\r.lotus.StatusR\x06status\")\n" +
	"\x13GetAdminUserListReq\x12\x12\n" +
	"\x04uids\x18\x01 \x03(\tR\x04uids\"c\n" +
	"\x14GetAdminUserListResp\x12$\n" +
	"\x04data\x18\x01 \x03(\v2\x10.lotus.AdminUserR\x04data\x12%\n" +
	"\x06status\x18\x02 \x01(\v2\r.lotus.StatusR\x06status\"\x80\x02\n" +
	"\n" +
	"Department\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x14\n" +
	"\x05brief\x18\x03 \x01(\tR\x05brief\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrl\x12\x18\n" +
	"\acatalog\x18\x05 \x01(\tR\acatalog\x12(\n" +
	"\x06leader\x18\x06 \x03(\v2\x10.lotus.AdminUserR\x06leader\x12(\n" +
	"\x06member\x18\a \x03(\v2\x10.lotus.AdminUserR\x06member\x12-\n" +
	"\bchildren\x18\b \x03(\v2\x11.lotus.DepartmentR\bchildren\"/\n" +
	"\x13GetAllDepartmentReq\x12\x18\n" +
	"\acatalog\x18\x01 \x01(\tR\acatalog\"h\n" +
	"\x18GetAllDepartmentResppone\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.lotus.DepartmentR\x04data\x12%\n" +
	"\x06status\x18\x02 \x01(\v2\r.lotus.StatusR\x06status2\xf6\x01\n" +
	"\x10AdminUserService\x12C\n" +
	"\x10GetAdminUserInfo\x12\x16.lotus.GetAdminUserReq\x1a\x17.lotus.GetAdminUserResp\x12K\n" +
	"\x10GetAdminUserList\x12\x1a.lotus.GetAdminUserListReq\x1a\x1b.lotus.GetAdminUserListResp\x12P\n" +
	"\x11GetAllDepartments\x12\x1a.lotus.GetAllDepartmentReq\x1a\x1f.lotus.GetAllDepartmentRespponeB\aZ\x05../pbb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_admin_proto_goTypes = []any{
	(*Status)(nil),                   // 0: lotus.Status
	(*AdminUser)(nil),                // 1: lotus.AdminUser
	(*GetAdminUserReq)(nil),          // 2: lotus.GetAdminUserReq
	(*GetAdminUserResp)(nil),         // 3: lotus.GetAdminUserResp
	(*GetAdminUserListReq)(nil),      // 4: lotus.GetAdminUserListReq
	(*GetAdminUserListResp)(nil),     // 5: lotus.GetAdminUserListResp
	(*Department)(nil),               // 6: lotus.Department
	(*GetAllDepartmentReq)(nil),      // 7: lotus.GetAllDepartmentReq
	(*GetAllDepartmentResppone)(nil), // 8: lotus.GetAllDepartmentResppone
}
var file_admin_proto_depIdxs = []int32{
	1,  // 0: lotus.GetAdminUserResp.data:type_name -> lotus.AdminUser
	0,  // 1: lotus.GetAdminUserResp.status:type_name -> lotus.Status
	1,  // 2: lotus.GetAdminUserListResp.data:type_name -> lotus.AdminUser
	0,  // 3: lotus.GetAdminUserListResp.status:type_name -> lotus.Status
	1,  // 4: lotus.Department.leader:type_name -> lotus.AdminUser
	1,  // 5: lotus.Department.member:type_name -> lotus.AdminUser
	6,  // 6: lotus.Department.children:type_name -> lotus.Department
	6,  // 7: lotus.GetAllDepartmentResppone.data:type_name -> lotus.Department
	0,  // 8: lotus.GetAllDepartmentResppone.status:type_name -> lotus.Status
	2,  // 9: lotus.AdminUserService.GetAdminUserInfo:input_type -> lotus.GetAdminUserReq
	4,  // 10: lotus.AdminUserService.GetAdminUserList:input_type -> lotus.GetAdminUserListReq
	7,  // 11: lotus.AdminUserService.GetAllDepartments:input_type -> lotus.GetAllDepartmentReq
	3,  // 12: lotus.AdminUserService.GetAdminUserInfo:output_type -> lotus.GetAdminUserResp
	5,  // 13: lotus.AdminUserService.GetAdminUserList:output_type -> lotus.GetAdminUserListResp
	8,  // 14: lotus.AdminUserService.GetAllDepartments:output_type -> lotus.GetAllDepartmentResppone
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
